In [25]:
import os
import pandas as pd
PATH = os.path.join("data","baseball_players2022diff.tsv")
#PATH = os.path.join("data","baseball_players_sample.tsv")

names = ["name","team","dummy0","full_pron","family_pron","given_pron"]
df = pd.read_csv(PATH, sep="\t",header=None, names = names)
# dummy0列を削除する
df = df.drop(columns=["dummy0"])
df.head()

     name    team    full_pron family_pron given_pron
0  粟飯原龍之介    DeNA  アイバラ リュウノスケ        アイバラ     リュウノスケ
1     青木修      阪神      アオキ オサム         アオキ        オサム
2    青木重市      阪神    アオキ ジュウイチ         アオキ      ジュウイチ
3    青田潤三  中日-トンボ    アオタ ジュンゾウ         アオタ      ジュンゾウ
4    青戸英夫     トンボ      アオト ヒデオ         アオト        ヒデオ

In [48]:
#nameをカッコでバラす関数を定義
import re
def format_name(name):
  """_summary_

  Args:
      name (str): name

  Returns:
      list[str]: names
  """
  # 全角カッコを半確認する
  name = name.translate(str.maketrans("（）", "()"))
  #スペース削除
  name = "".join(name.split())
  #カッコでスプリット
  namelist = re.split("[()]",name)
  # 空の要素を削除
  namelist = [x for x in namelist if x != ""]
  # あいうえおの昇順ソート
  namelist.sort()
  return namelist

print(format_name("奥田和男（旭和男）"))
print(format_name("旭和男（奥田和男）"))

['奥田和男', '旭和男']
['奥田和男', '旭和男']

In [27]:
def get_ids(names, teams, cnt={}):  
  ids = []
  for name, team in zip(names, teams):
    name = format_name(name)[0]
    team = team.split("-")[0]
    id_head = "{}_{}".format(name, team)
    id = "{}_{}".format(id_head, str(cnt.get(id_head,0)).zfill(5))
    ids.append(id)
    cnt[id_head] = cnt.get(id_head,0) + 1
  return ids

get_ids(df["name"],df["team"],{})

['粟飯原龍之介_DeNA_00000',
 '青木修_阪神_00000',
 '青木重市_阪神_00000',
 '青田潤三_中日_00000',
 '青戸英夫_トンボ_00000',
 '赤星優志_巨人_00000',
 '秋山正雲_ロッテ_00000',
 '麻田勝也_阪神_00000',
 '奥田和男_中日_00000',
 '浅利光博_大洋_00000',
 '穴吹祐司_阪急_00000',
 '阿部和広_日本ハム_00000',
 '新井智博_巨人_00000',
 '荒川俊男_巨人_00000',
 '有薗直輝_日本ハム_00000',
 '有本義明_ダイエー_00000',
 'アリスメンディ・アルカンタラ_日本ハム_00000',
 'ダリエル・アルバレス_ソフトバンク_00000',
 'フランク・アルバレス_中日_00000',
 'アレクサンダー・アルメンタ_ソフトバンク_00000',
 'ドリュー・アンダーソン_広島_00000',
 'マット・アンドリース_巨人_00000',
 '飯田茂男_西武_00000',
 '家永伸彦_高橋_00000',
 '伊貸文秀_中日_00000',
 '生田裕之_中日_00000',
 '猪口明宏_巨人_00000',
 '井口龍三_南海_00000',
 '池田正憲_巨人_00000',
 '池田芳己_阪神_00000',
 '池田来翔_ロッテ_00000',
 '池田陵真_オリックス_00000',
 '池畑満也_ロッテ_00000',
 '池辺忠則_西鉄・太平洋_00000',
 '井坂興_巨人_00000',
 '井崎燦志郎_ソフトバンク_00000',
 '井沢武則_阪神_00000',
 '石川光一_中日_00000',
 '石田隼都_巨人_00000',
 '石橋功行_阪神_00000',
 '石渕国博_広島_00000',
 '石森大誠_中日_00000',
 '泉田喜義_巨人_00000',
 '磯崎慎二_南海_00000',
 '板垣一彦_阪神_00000',
 '板野強_トンボ・高橋_00000',
 '市川達也_ロッテ_00000',
 '伊藤茂_タイガース_00000',
 '伊藤舜二_阪神_00000',
 '伊藤正彦_阪神_00000',
 '伊藤稜_阪神_00000',
 '稲垣秀次_巨人_00000',
 '稲生高善_南海_00000',
 '稲葉進_大洋_00000',
 '井上重信_近鉄_00000',
 '井上武_巨人_00000',
 '猪原利裕_西武_00000',
 '井股明_大和軍_00000',
 '今井茂_阪急_00000',
 '今岡均_中日_00000',
 '井村典夫_阪神_00000',
 '入江淳_阪神_00000',
 '入生比佐男_阪急_00000',
 '岩佐基治_阪神_00000',
 '岩田幸宏_ヤクルト_00000',
 '岩月宏之_中日_00000',
 '岩間章泰_阪神_00000',
 'ジャンセン_西武_00000',
 'アーロン・ウィルカーソン_阪神_00000',
 '上坂嘉彦_南海_00000',
 '上田正則_ロッテ_00000',
 '上野新_巨人_00000',
 'アダム・ウォーカー_巨人_00000',
 '鵜飼航丞_中日_00000',
 '浮島徹士_ロッテ_00000',
 '牛山晃一_阪神_00000',
 '勝昭_近鉄_00000',
 '卯津羅勝昭_近鉄_00000',
 '宇都宗夫_阪神_00000',
 '江崎毅_近鉄_00000',
 '江島聖一_阪神_00000',
 '江城哲雄_近鉄_00000',
 '枝川正典_阪神_00000',
 '衛藤雅登_日拓_00000',
 'ディートリック・エンス_西武_00000',
 '遠藤繁浩_オリックス_00000',
 '翁田大勢_巨人_00000',
 '大石和宏_阪神_00000',
 '大石昌義_阪神_00000',
 '大河原翔_楽天_00000',
 '大木利男_阪神_00000',
 '大串尚弘_阪神_00000',
 '大串祥寅_阪神_00000',
 '大倉正貢_阪神_00000',
 '大越弘_阪神_00000',
 '大里昂生_オリックス_00000',
 '大島中_中日_00000',
 '大島義雄_阪神_00000',
 '大竹風雅_ソフトバンク_00000',
 '大津綾也_巨人_00000',
 '大西正昭_阪神_00000',
 '大西正裕_日本ハム_00000',
 '大橋武尊_DeNA_00000',
 '大和田透_阪神_00000',
 '岡昭彦_巨人_00000',
 '小笠原正一_阪神_00000',
 '岡田耕司_近鉄_00000',
 '岡田忠雄_巨人_00000',
 '岡田英樹_太平洋_00000',
 '岡田悠希_巨人_00000',
 '岡留英貴_阪神_00000',
 '岡部宏_巨人_00000',
 '岡本吉守_ダイエー_00000',
 '岡本良_阪神_00000',
 '小川勝彦_高橋_00000',
 '小川忠幸_阪急_00000',
 '奥昌男_広島_00000',
 '奥田修_阪神_00000',
 '奥田和男_中日_00001',
 '小倉泰男_阪神_00000',
 'ブライアン・オグレディ_西武_00000',
 '小沢祐規_大洋_00000',
 '小原五郎_巨人_00000',
 '表浩太郎_阪神_00000',
 '加賀元_中日_00000',
 '柿原功_トンボ_00000',
 '笠原敦郎_大洋_00000',
 '風間球打_ソフトバンク_00000',
 '樫出三郎_阪神_00000',
 '柏木裕_阪神_00000',
 '梶原昂希_DeNA_00000',
 'アレックス・カステヤーノス_巨人_00000',
 '片山春男_阪神_00000',
 '嘉手苅浩太_ヤクルト_00000',
 '加藤邦彦_ロッテ_00000',
 '加藤邦彦_ロッテ_00001',
 '加藤洸稀_ソフトバンク_00000',
 '加藤晴空_ソフトバンク_00000',
 '加藤英樹_ダイエー_00000',
 '加藤良治_近鉄_00000',
 '金富泰洋_中日_00000',
 '金子歩_中日_00000',
 '金子貴博_日本ハム_00000',
 '金原鉄夫_阪神_00000',
 '上川畑大悟_日本ハム_00000',
 '上妻恒幸_日本ハム_00000',
 '上沼秀人_阪神_00000',
 '上別府幸一_西鉄_00000',
 '上森合直幸_ロッテ_00000',
 '亀田啓太_巨人_00000',
 '鴨打瑛二_巨人_00000',
 '鴨志田仙_広島_00000',
 '鴨田肇_阪神_00000',
 'D.J.カラスコ_ソフトバンク_00000',
 'ギジェルモ・ガルシア_中日_00000',
 'ホセ・アドリス・ガルシア_巨人_00000',
 'フレディ・ガルビス_ソフトバンク_00000',
 '川嵜陽仁_巨人_00000',
 '川島日出雄_太平洋・クラウン_00000',
 '河瀬雅英_近鉄_00000',
 '川中圭三_広島_00000',
 '川西愑治_阪神_00000',
 '川根康久_南海_00000',
 '川村啓真_西武_00000',
 '川村友斗_ソフトバンク_00000',
 '川本浩司_大映_00000',
 'ジョン・ガント_日本ハム_00000',
 '菊池大稀_巨人_00000',
 '菊地敏郎_広島_00000',
 '岸佳之_近鉄_00000',
 '木田優_中日_00000',
 '北崎純一_広島_00000',
 '北田嘉秀_南海_00000',
 '北戸忠_大洋_00000',
 '北村哲治_中日_00000',
 '北山亘基_日本ハム_00000',
 '城戸剛_トンボ_00000',
 'パトリック・キブレハン_ヤクルト_00000',
 '木村大成_ソフトバンク_00000',
 '木村隆昭_阪急_00000',
 '木村義光_高橋・トンボ_00000',
 '京本眞_巨人_00000',
 '清本登志也_近鉄_00000',
 '桐敷拓馬_阪神_00000',
 '桐山明佳_日本ハム_00000',
 '久木山亮_太平洋_00000',
 '草場康郎_ロッテ_00000',
 '草深正広_広島_00000',
 '櫛笥厚正_中日_00000',
 '楠本一夫_阪神_00000',
 '工藤慎明_阪神_00000',
 '久保田一_東映・日拓_00000',
 '倉橋孝治_高橋_00000',
 'ブルックス・クリスキー_DeNA_00000',
 '黒田将矢_西武_00000',
 '黒原拓未_広島_00000',
 '畔柳亨丞_日本ハム_00000',
 'カイル・ケラー_阪神_00000',
 'ケリン_ヤクルト_00000',
 'タイロン・ゲレーロ_ロッテ_00000',
 '小池貴志_中日_00000',
 '小池均_近鉄_00000',
 '小泉泰重_巨人_00000',
 'A.J.コール_ヤクルト_00000',
 '古賀悠斗_西武_00000',
 '小木田敦也_オリックス_00000',
 '小園健太_DeNA_00000',
 '後藤将和_ダイエー_00000',
 '後藤正美_阪神_00000',
 '小林一夫_日拓_00000',
 '小林一史_広島_00000',
 '小森航大郎_ヤクルト_00000',
 '斎藤輝美_西鉄・太平洋_00000',
 '酒井啓吾_阪神_00000',
 '酒井貢_阪神_00000',
 '榊原龍男_ダイエー_00000',
 '阪口樂_日本ハム_00000',
 '坂口慶三郎_阪神_00000',
 '坂口浩則_近鉄_00000',
 '坂田怜_広島_00000',
 '坂本勉_日本ハム_00000',
 '坂本義雄_阪神_00000',
 '嵯峨山幹雄_阪神_00000',
 '崎山嗣盛_阪神_00000',
 '佐久間拓斗_ソフトバンク_00000',
 '佐々木伸_広島_00000',
 '笹原操希_巨人_00000',
 '佐藤栄一_タイガース_00000',
 '佐藤薫_ロッテ_00000',
 '佐藤隼輔_西武_00000',
 '佐藤琢磨_ソフトバンク_00000',
 '佐藤一_オリックス_00000',
 '佐藤秀信_オリックス_00000',
 '佐野浩一_日本ハム_00000',
 '沢田守_阪急_00000',
 '沢幡誠士_広島_00000',
 'ネイト・シアーホルツ_広島_00000',
 '潮田輝雄_阪神_00000',
 '柴田大地_ヤクルト_00000',
 '冷水美夫_阪神_00000',
 '下地勝治_広島_00000',
 'マルコ・シモン_ソフトバンク_00000',
 'ケビン・シャッケルフォード_DeNA_00000',
 'ジャンセン_西武_00001',
 'マット・シューメーカー_巨人_00000',
 '上甲秀男_阪神_00000',
 '白井仁_日本ハム_00000',
 '白次謙二_中日_00000',
 '代木大和_巨人_00000',
 '新家颯_広島_00000',
 'アンドリュー・スアレス_ヤクルト_00000',
 '末包昇大_広島_00000',
 '菅井信也_西武_00000',
 '鈴木延王_トンボ_00000',
 '鈴木大和_巨人_00000',
 '鈴木勇斗_阪神_00000',
 '鈴村充男_阪神_00000',
 '須田清見_ロッテ_00000',
 'グレン・スパークマン_オリックス_00000',
 'バーチ・スミス_西武_00000',
 '隅田知一郎_西武_00000',
 '関根毅_ヤクルト_00000',
 '園部佳太_オリックス_00000',
 '杣田登_阪神_00000',
 '征矢高行_巨人_00000',
 'ニック・ターリー_広島_00000',
 '泰勝利_楽天_00000',
 '高泉秀輝_ヤクルト_00000',
 '高木翔斗_広島_00000',
 '高木隆司_阪神_00000',
 '高木昇_阪神_00000',
 '高木睦雄_阪神_00000',
 '高岸佳宏_近鉄_00000',
 '高田竜星_巨人_00000',
 '高梨芳昌_巨人_00000',
 '高野慎哉_日本ハム_00000',
 'ボー_西武_00000',
 '滝道章_阪神_00000',
 '滝澤夏央_西武_00000',
 '滝照清正_大洋_00000',
 '滝野通則_タイガース_00000',
 '瀧本将生_ソフトバンク_00000',
 '武井祐行_西武_00000',
 '武内淳二_阪神_00000',
 '竹内史英_阪急_00000',
 '武田章吾_西武_00000',
 '竹野博士_阪神_00000',
 '竹原比呂志_南海_00000',
 '竹峰丈太郎_阪神_00000',
 '竹山日向_ヤクルト_00000',
 '但田裕介_阪神_00000',
 '田島俊英_巨人_00000',
 '田尻一郎_南海_00000',
 '但木健一郎_中日_00000',
 '達孝太_日本ハム_00000',
 '田中久義_阪急_00000',
 '田中博樹_阪神_00000',
 '田中楓基_ロッテ_00000',
 '田中怜利ハモンド_ソフトバンク_00000',
 '田上一秀_南海_00000',
 'ジョアン・タバ―レス_広島_00000',
 '玉川照知朗_高橋_00000',
 '玉城正富_阪神_00000',
 '田村浩一_阪神_00000',
 '田村俊介_広島_00000',
 '田村登志親_ロッテ_00000',
 'タイラー・チャットウッド_ソフトバンク_00000',
 'ヨヘルミン・チャベス_オリックス_00000',
 '仲元寺政昭_日本ハム_00000',
 '辻邦男_阪神_00000',
 '辻正孝_中日_00000',
 '辻嘉美_阪神_00000',
 '土橋修_阪神_00000',
 '土谷賢一_阪神_00000',
 'フリアン・ティマ_巨人_00000',
 'ホセ・デラクルーズ_巨人_00000',
 '徳山壮真_DeNA_00000',
 '富田龍_巨人_00000',
 '外山雅則_阪神_00000',
 '豊岡昭久_南海_00000',
 '豊島寛_中日_00000',
 '豊田寛_阪神_00000',
 '豊田実_大洋_00000',
 '豊原経久_阪神_00000',
 '豊平晋一_阪神_00000',
 '豊村健泰_近鉄_00000',
 '仲忠雄_阪神_00000',
 '中川勇斗_阪神_00000',
 '中沢泰司_阪神_00000',
 '中島浩一_近鉄_00000',
 '中島孝盛_阪神_00000',
 '中島裕司_近鉄_00000',
 '中島愛和_中日_00000',
 '永島田輝斗_ロッテ_00000',
 '仲田慶介_ソフトバンク_00000',
 '永田哲也_西鉄_00000',
 '中谷賢平_阪神_00000',
 '長幡忠夫_阪神_00000',
 '中村公信_阪神_00000',
 '中村健人_広島_00000',
 '中村基昭_広島_00000',
 '中村来生_広島_00000',
 '永安清巳_南海_00000',
 '中山重夫_阪神_00000',
 '中山誠吾_西武_00000',
 '夏目隆司_阪急_00000',
 '難波孝将_南海_00000',
 '西茂夫_阪神_00000',
 '西浦丈夫_阪神_00000',
 '西垣雅矢_楽天_00000',
 '西上正人_南海_00000',
 '西嶋賢治_ロッテ_00000',
 '西出佐夫郎_阪神_00000',
 '西村孜_阪神_00000',
 '西村義人_南海_00000',
 '西山進_西武_00000',
 '似鳥功_阪神_00000',
 '新田法昭_阪神_00000',
 '新田幸夫_広島_00000',
 'レナート・ヌニエス_日本ハム_00000',
 '正行_高橋_00000',
 '政行_高橋_00000',
 '根建忍_広島_00000',
 '野口智哉_オリックス_00000',
 '野口理夫_近鉄_00000',
 '野村勇_ソフトバンク_00000',
 'スコット・ハイネマン_巨人_00000',
 '橋口敏英_巨人_00000',
 '橋口美利_ヤクルト_00000',
 '長谷川澂_中日_00000',
 '長谷川威展_日本ハム_00000',
 '羽田慎之介_西武_00000',
 '畑口健二_大洋_00000',
 '花田侑樹_巨人_00000',
 '羽田広伸_南海_00000',
 '馬場哲也_阪神_00000',
 '浜田総国_中日_00000',
 '林敬治_近鉄_00000',
 '林雅晃_広島_00000',
 '林正毅_広島_00000',
 '林真人_阪神_00000',
 '速水将太_ロッテ_00000',
 '速水隆成_日本ハム_00000',
 '原正俊_巨人_00000',
 '原之後富則_国鉄_00000',
 'セサル・バルガス_オリックス_00000',
 'ブレイビック・バレラ_オリックス_00000',
 'ボビー・バレンタイン_ロッテ_00000',
 '東出直也_DeNA_00000',
 '樋口和生_阪神_00000',
 'ジェシー・ビドル_オリックス_00000',
 '平川敏明_南海_00000',
 'デュアン・ビロウ_DeNA_00000',
 '広野准一_日本ハム_00000',
 '廣畑敦也_ロッテ_00000',
 'マイロン・フェリックス_ソフトバンク_00000',
 '深沢鳳介_DeNA_00000',
 '福井努_近鉄_00000',
 '福島蓮_日本ハム_00000',
 '福永奨_オリックス_00000',
 '福元悠真_中日_00000',
 '藤沢新六_阪神_00000',
 '藤野恵音_ソフトバンク_00000',
 '藤本雄司_阪神_00000',
 '伏島良平_巨人_00000',
 '淵上魔基_阪急_00000',
 '船津隆介_太平洋_00000',
 'ブライト健太_中日_00000',
 'ホアン・フランシスコ_巨人_00000',
 '古市尊_西武_00000',
 '別所誠司_日本ハム_00000',
 '部矢重幸_金鯱_00000',
 'フランケリー・ヘラルディーノ_ソフトバンク_00000',
 'ラファエル・ペレス_中日_00000',
 '外園正_巨人_00000',
 '星野真生_中日_00000',
 'ケリン_ヤクルト_00001',
 'グレゴリー・ポランコ_巨人_00000',
 'コディ・ポンセ_日本ハム_00000',
 '前川誠太_広島_00000',
 '前川右京_阪神_00000',
 '前田銀治_楽天_00000',
 '前田友行_阪神_00000',
 '前田友行_阪神_00001',
 '槙尾達男_阪神_00000',
 'ライアン・マクブルーム_広島_00000',
 '正木智也_ソフトバンク_00000',
 '政山恵一_サンケイ_00000',
 '増岡正也_ロッテ_00000',
 '松井友飛_楽天_00000',
 '松浦慶斗_日本ハム_00000',
 '松尾勝彦_阪神_00000',
 '松尾裕二_南海_00000',
 '松岡一雄_阪神_00000',
 'ジョー・マッカーシー_オリックス_00000',
 '松川虎生_ロッテ_00000',
 '松沢勉_阪神_00000',
 '松永満_阪神_00000',
 '松畑佳明_阪急_00000',
 '松原由昌_巨人_00000',
 '松本和弘_広島_00000',
 '松本信二_日本ハム_00000',
 '真部繁敏_南海_00000',
 'ハンセル・マルセリーノ_DeNA_00000',
 'ホセ・マルモレホス_楽天_00000',
 '丸山一男_阪神_00000',
 '丸山和郁_ヤクルト_00000',
 '丸山武彦_阪神_00000',
 '三浦銀二_DeNA_00000',
 '三浦正造_阪神_00000',
 '三浦瑞樹_ソフトバンク_00000',
 '三木茂_日本ハム_00000',
 'ダニエル・ミサキ_巨人_00000',
 '三代祥貴_ソフトバンク_00000',
 '水谷実智郎_中日_00000',
 '水野達稀_日本ハム_00000',
 '御手洗久文_近鉄_00000',
 '三橋孝明_トンボ_00000',
 '三原一夫_阪神_00000',
 '三本政之_近鉄_00000',
 '味谷大誠_中日_00000',
 '宮川晃_日本ハム_00000',
 '宮田正直_ダイエー_00000',
 '宮本尊義_阪神_00000',
 '宮本尊義_阪神_00001',
 '宮森智志_楽天_00000',
 '椋木蓮_オリックス_00000',
 '村井博_阪神_00000',
 '村上勤_トンボ_00000',
 '村川凪_DeNA_00000',
 '村川幸男_阪神_00000',
 '村田弘_阪神_00000',
 '村山亮介_ロッテ_00000',
 'アガスティン・ムリーロ_楽天_00000',
 '茂木武夫_トンボ_00000',
 '之雄_中日_00000',
 '望月勝_高橋_00000',
 '一也_中日_00000',
 '森秀二_ダイエー_00000',
 '森翔平_広島_00000',
 '森宝生_西武_00000',
 '森忠仁_阪神_00000',
 '森岡淳_中日_00000',
 '森木大智_阪神_00000',
 '森重泰浩_広島_00000',
 '森本智_日本ハム_00000',
 '森山隆男_近鉄_00000',
 '森山学_ロッテ_00000',
 'ブレント・モレル_オリックス_00000',
 '八木彬_ロッテ_00000',
 '薬師神繁男_大洋_00000',
 '安田悠馬_楽天_00000',
 '柳川大晟_日本ハム_00000',
 '柳澤大空_楽天_00000',
 '山崎琢磨_ソフトバンク_00000',
 '山崎公晴_中日_00000',
 '山地馨_阪神_00000',
 '山下一義_阪神_00000',
 '山下輝_ヤクルト_00000',
 '山田茂_阪神_00000',
 '山田譲治_阪神_00000',
 '山田龍聖_巨人_00000',
 '山中尭之_オリックス_00000',
 '山本恵大_ソフトバンク_00000',
 '山本利一_南海_00000',
 '横井啓二_阪神_00000',
 '横倉豊_日本ハム_00000',
 '横山楓_オリックス_00000',
 '吉岡賢治郎_西武_00000',
 '吉川雄大_楽天_00000',
 '吉川盛男_ヤクルト_00000',
 '吉田邦彦_ロッテ_00000',
 '吉田征人_阪急・オリックス_00000',
 '吉武正成_日本ハム_00000',
 '吉野創士_楽天_00000',
 '与那城隆_巨人_00000',
 '米川清二_阪神_00000',
 'ウールジー・ライス_近鉄_00000',
 'ミッチ・ライブリー_日本ハム_00000',
 'ランへル・ラベロ_オリックス_00000',
 'ジェイコブ・ワゲスパック_オリックス_00000',
 '渡辺邦彦_阪神_00000',
 '渡部遼人_オリックス_00000',
 '和中史郎_南海_00000']

In [28]:
df["id"] = get_ids(df["name"],df["team"])
df

,name,team,full_pron,family_pron,given_pron,id
0,粟飯原龍之介,DeNA,アイバラ リュウノスケ,アイバラ,リュウノスケ,粟飯原龍之介_DeNA_00000
1,青木修,阪神,アオキ オサム,アオキ,オサム,青木修_阪神_00000
2,青木重市,阪神,アオキ ジュウイチ,アオキ,ジュウイチ,青木重市_阪神_00000
3,青田潤三,中日-トンボ,アオタ ジュンゾウ,アオタ,ジュンゾウ,青田潤三_中日_00000
4,青戸英夫,トンボ,アオト ヒデオ,アオト,ヒデオ,青戸英夫_トンボ_00000
...,...,...,...,...,...,...
519,ランへル・ラベロ,オリックス,ランヘル・ラベロ,ラベロ,ランヘル,ランへル・ラベロ_オリックス_00000
520,ジェイコブ・ワゲスパック,オリックス,ジェイコブ・ワゲスパック,ワゲスパック,ジェイコブ,ジェイコブ・ワゲスパック_オリックス_00000
521,渡辺邦彦,阪神,ワタナベ クニヒコ,ワタナベ,クニヒコ,渡辺邦彦_阪神_00000
522,渡部遼人,オリックス,ワタナベ ハルト,ワタナベ,ハルト,渡部遼人_オリックス_00000
523,和中史郎,南海,ワナカ シロウ,ワナカ,シロウ,和中史郎_南海_00000

In [29]:
# 姓名分離するためのクラス
from namedivider import NameDivider
class Divider:
  def __init__(self):
    self.name_divider = NameDivider()
  def devide_jp_name(self,name):
    divided_name = self.name_divider.divide_name(name).to_dict()
    return divided_name
  def devide_foreign_name(self,name):
    sep = '・'
    family = name.split(sep)[-1]
    given = sep.join(name.split(sep)[:-1])
    #sepが複数含まれていたらscoreを下げる
    score = 1/(len(name.split(sep))-1)
    return {'family':family, 'given':given, 'score':score, 'algorithm': 'foreign_rule'}
  def divide_name(self,name):
    sep = '・'
    if len(name)==1:
      return {'family':name, 'given':'', 'score':1, 'algorithm': 'one_char_rule'}
    elif sep in name:
      return self.devide_foreign_name(name)
    else:
      return self.devide_jp_name(name)

divider = Divider()
df["name"].apply(divider.divide_name)

0      {'family': '粟飯原', 'given': '龍之介', 'separator':...
1      {'family': '青木', 'given': '修', 'separator': ' ...
2      {'family': '青木', 'given': '重市', 'separator': '...
3      {'family': '青田', 'given': '潤三', 'separator': '...
4      {'family': '青戸', 'given': '英夫', 'separator': '...
                             ...
519    {'family': 'ラベロ', 'given': 'ランへル', 'score': 1....
520    {'family': 'ワゲスパック', 'given': 'ジェイコブ', 'score'...
521    {'family': '渡辺', 'given': '邦彦', 'separator': '...
522    {'family': '渡部', 'given': '遼人', 'separator': '...
523    {'family': '和中', 'given': '史郎', 'separator': '...
Name: name, Length: 524, dtype: object

In [34]:
# 名前候補を列方向に展開
def expand_name(df_rows,name_key="name"):
  new_rows = []
  for index,row in df_rows.iterrows():
    name = row[name_key]
    namelist = format_name(name)
    for n in namelist:
      new_row = row.copy()
      new_row[name_key] = n
      new_rows.append(new_row)
  return pd.DataFrame(new_rows)

In [31]:

def add_separated_name_column(df, name_key="name"):
  df = df.copy()

  new_rows = []
  for index, row in df.iterrows():
    name = row[name_key]
    separated_name = divider.divide_name(name)
    row = {k:v for k,v in row.items()}
    row.update(separated_name)
    new_rows.append(row)
  
  return pd.DataFrame(new_rows)

add_separated_name_column(expand_name(df))

,name,team,full_pron,family_pron,given_pron,id,family,given,separator,score,algorithm
0,粟飯原龍之介,DeNA,アイバラ リュウノスケ,アイバラ,リュウノスケ,粟飯原龍之介_DeNA_00000,粟飯原,龍之介,,0.283697,kanji_feature
1,青木修,阪神,アオキ オサム,アオキ,オサム,青木修_阪神_00000,青木,修,,0.692655,kanji_feature
2,青木重市,阪神,アオキ ジュウイチ,アオキ,ジュウイチ,青木重市_阪神_00000,青木,重市,,0.507572,kanji_feature
3,青田潤三,中日-トンボ,アオタ ジュンゾウ,アオタ,ジュンゾウ,青田潤三_中日_00000,青田,潤三,,0.573842,kanji_feature
4,青戸英夫,トンボ,アオト ヒデオ,アオト,ヒデオ,青戸英夫_トンボ_00000,青戸,英夫,,0.549918,kanji_feature
...,...,...,...,...,...,...,...,...,...,...,...
538,ランへル・ラベロ,オリックス,ランヘル・ラベロ,ラベロ,ランヘル,ランへル・ラベロ_オリックス_00000,ラベロ,ランへル,NaN,1.000000,foreign_rule
539,ジェイコブ・ワゲスパック,オリックス,ジェイコブ・ワゲスパック,ワゲスパック,ジェイコブ,ジェイコブ・ワゲスパック_オリックス_00000,ワゲスパック,ジェイコブ,NaN,1.000000,foreign_rule
540,渡辺邦彦,阪神,ワタナベ クニヒコ,ワタナベ,クニヒコ,渡辺邦彦_阪神_00000,渡辺,邦彦,,0.574853,kanji_feature
541,渡部遼人,オリックス,ワタナベ ハルト,ワタナベ,ハルト,渡部遼人_オリックス_00000,渡部,遼人,,0.574584,kanji_feature
542,和中史郎,南海,ワナカ シロウ,ワナカ,シロウ,和中史郎_南海_00000,和中,史郎,,0.562666,kanji_feature

In [ ]:

df2 = add_separated_name_column(expand_name(df))

In [40]:
# フルネーム、姓、名を別行に分けて、列名を選手表の形式にする
def make_player_table(df):
  new_rows = []
  for index, row in df.iterrows():
    surfaces = [row["name"],row["family"],row["given"]]
    pronunciations = [row["full_pron"],row["family_pron"],row["given_pron"]]
    types = ["full","family","given"]
    team = row["team"]
    id = row["id"]
    original = row["original"]
    for surface, pronunciation, type in zip(surfaces, pronunciations, types):
      if not surface: continue
      new_row = {
        "id":id,
        "original":original,
        "team":team,
        "surface": surface,
        "pronunciation": pronunciation,
        "type": type,
        "org_id":id,
      }
      new_rows.append(new_row)
  return pd.DataFrame(new_rows)

df2 = df.copy()
df2["original"] = df["name"]
df2 = expand_name(df2)
df2 = add_separated_name_column(df2)
df2 = make_player_table(df2)
df2

KeyError: 'name'

In [36]:
# 名字分割結果のチェック
import os
import pandas as pd
PATH = os.path.join("data","baseball_players2022diff.tsv")
#PATH = os.path.join("data","baseball_players_sample.tsv")

names = ["name","team","dummy0","full_pron","family_pron","given_pron"]
df = pd.read_csv(PATH, sep="\t",header=None, names = names)
# dummy0列を削除する
df = df.drop(columns=["dummy0"])
df["original"] = df["name"]
df["id"] = get_ids(df["name"],df["team"])
df = expand_name(df)
df = add_separated_name_column(df)
df.to_clipboard(sep="\t",index=False)
#df2.to_csv("data/baseball_players_table_2022diff.tsv",sep="\t",index=False)

In [52]:
df = pd.read_clipboard(sep="\t")
#df["id"] = get_ids(df["name"],df["team"],{})
df = make_player_table(df)
df.to_clipboard(sep="\t",index=False)